- name: "Install dependencies"
  become: true
  shell: |
      cd ./backend
      npm i
      npm run build

- name: "Run migrations"
  become: true
  shell: |
      cd ./backend
      npm run migrations