- name: "Install dependencies"
  become: true
  shell: |
      cd ./backend
      npm -v
      node -v
      npm i

- name: "Run migrations"
  become: true
  shell: |
      cd ./backend
      npm run migrations