version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"

  #build phase
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: cd ./frontend && npm i && npm run build 

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: cd ./backend && npm i && npm run build

  #Unit test phase
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Frontend Test
          command: | 
            cd ./frontend && npm i
            npm install --save-dev jest-junit
            npm run test --ci --reporters=default --reporters=jest-junit
          
      - store_test_results:
          path: ./frontend/test-results/
      - store_artifacts:
          path: ./frontend/test-results/jest/results.xml
    
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
    
          name: Backend Test
          command: |
            cd ./backend && npm i
            npm install --save-dev jest-junit
            npm run test --ci --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ./backend/test-results/
      - store_artifacts:
          path: ./backend/test-results/jest/results.xml

  #tests for security
  frontend-security:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Frontend Security Test
          command: | 
            cd ./frontend && npm i
            npm audit --audit-level=critical
       
  backend-security:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          name: Backend Security Test
          command: |
            cd ./backend && npm i
            npm audit --audit-level=critical


workflows:
  default:
    jobs:
      #- hello-world
      #- build-frontend:
      #   requires:
      #     - hello-world
      #- build-backend:
      #   requires:
      #     - hello-world
      #- test-frontend:
      #   requires:
      #     - build-frontend
      #     - build-backend
      #- test-backend:
      #   requires:
      #     - build-backend
      #     - build-frontend
      #- frontend-security:
      #   requires:
      #     - test-frontend
      #     - test-backend
      #- backend-security:
      #   requires:
      #     - test-backend
      #     - test-frontend
      - frontend-security
      - backend-security
           
