
- name: Compress directory
  archive:
    path: ../../backend
    dest: home/ubuntu/backend.tar.gz


- name: Extract directory to ec2 instance
  become: true
  unarchive:
    src: /home/ubuntu/backend.tar.gz
    dest: /home/ubuntu