
- name: Compress directory
  archive:
    path: ../../backend
    dest: ./backend.tar.gz


- name: Extract directory to ec2 instance
  become: true
  unarchive:
    src: /root/project/.circleci/ansible/backend.tar.gz
    dest: /home/ubuntu